stages:
  - test
  - release

eslint:
  stage: test
  image: node:8.9-alpine
  tags:
    - docker
  script:
    - yarn install
    - yarn eslint

build:
  stage: release
  tags:
    - shell
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - release
    - master
